import { precacheAndRoute, cleanupOutdatedCaches, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { NetworkFirst, CacheFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { ExpirationPlugin } from 'workbox-expiration';
import { RangeRequestsPlugin } from 'workbox-range-requests';

// ─── 1) Precache all assets generated by Vite (HTML, JS, CSS, icons) ─────────
precacheAndRoute(self.__WB_MANIFEST || [], {
  ignoreURLParametersMatching: [/.*/]
});
cleanupOutdatedCaches();

// ─── 2) Instant activation ───────────────────────────────────────────────────
self.addEventListener("install", () => {
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    // Delete old/corrupted material caches, then claim clients
    caches.keys().then((cacheNames) =>
      Promise.all(
        cacheNames
          .filter((name) => name === 'cic-offline-materials-v1')
          .map((name) => caches.delete(name))
      )
    ).then(() => self.clients.claim())
  );
});

// ─── 3) SPA Navigation Route — serves precached index.html on ANY route offline
try {
  registerRoute(
    new NavigationRoute(createHandlerBoundToURL('index.html'), {
      denylist: [
        new RegExp('^/pdfjs-viewer/'),
        new RegExp('^/api/')
      ]
    })
  );
} catch (e) {
  console.warn('[SW] Failed to bind to index.html, trying /index.html', e);
  registerRoute(
    new NavigationRoute(createHandlerBoundToURL('/index.html'), {
      denylist: [
        new RegExp('^/pdfjs-viewer/'),
        new RegExp('^/api/')
      ]
    })
  );
}

// ─── 3.1) Cache-first for all same-origin static chunks (/assets/*.js, /assets/*.css)
registerRoute(
  ({ url }) => url.origin === self.location.origin && url.pathname.startsWith('/assets/'),
  new CacheFirst({
    cacheName: 'cic-assets-v1',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 150,
        maxAgeSeconds: 30 * 24 * 60 * 60,
      }),
    ],
  })
);

// ─── 4) Supabase REST API (Network-first with cache fallback, stale data offline)
registerRoute(
  ({ url }) => url.hostname.includes('supabase.co') && url.pathname.startsWith('/rest/'),
  new NetworkFirst({
    cacheName: 'cic-api-data-v1',
    networkTimeoutSeconds: 4,
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 7 * 24 * 60 * 60, // 7 days
      }),
    ],
  })
);

// ─── 5) Supabase Storage & Cloudflare R2 (Stale-While-Revalidate for materials)
// Uses SWR so cached files load instantly but are refreshed in the background,
// preventing stale/corrupted PDFs from persisting forever.
const isMaterialRequest = (url) =>
  (url.hostname.includes('supabase.co') && url.pathname.includes('/storage/')) ||
  url.hostname.includes('r2.cloudflarestorage.com') ||
  url.hostname.includes('r2.dev');

// 5.0) Byte-range requests (pdf.js chunked loading, video seeking).
// Without this, a cached full file was returned for a Range request, which breaks
// pdf.js ("0 of 0" blank viewer). Serve a proper 206 slice from the cache when we
// have the whole file, otherwise go to the network. Partial (206) responses are never cached.
registerRoute(
  ({ url, request }) => isMaterialRequest(url) && request.headers.has('range'),
  new CacheFirst({
    cacheName: 'cic-offline-materials-v2',
    plugins: [
      new CacheableResponsePlugin({ statuses: [200] }),
      new RangeRequestsPlugin(),
    ],
  })
);

registerRoute(
  ({ url }) => isMaterialRequest(url),
  new StaleWhileRevalidate({
    cacheName: 'cic-offline-materials-v2',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [200],
      }),
      new ExpirationPlugin({
        maxEntries: 300,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
      }),
    ],
  })
);

// ─── 6) Google Fonts stylesheets (Stale-While-Revalidate) ─────────────────────
registerRoute(
  ({ url }) => url.hostname === 'fonts.googleapis.com',
  new StaleWhileRevalidate({
    cacheName: 'cic-google-fonts-stylesheets',
  })
);

// ─── 7) Google Fonts webfonts (Cache-first) ──────────────────────────────────
registerRoute(
  ({ url }) => url.hostname === 'fonts.gstatic.com',
  new CacheFirst({
    cacheName: 'cic-google-fonts-webfonts',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 30,
        maxAgeSeconds: 365 * 24 * 60 * 60, // 1 year
      }),
    ],
  })
);

// ─── 8) Images (Stale-While-Revalidate) ──────────────────────────────────────
registerRoute(
  ({ request }) => request.destination === 'image',
  new StaleWhileRevalidate({
    cacheName: 'cic-images-v1',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 60,
        maxAgeSeconds: 30 * 24 * 60 * 60,
      }),
    ],
  })
);

// ─── 9) Push Notification Handler ───────────────────────────────────────────
self.addEventListener("push", (event) => {
  if (!event.data) {
    console.log("[SW] Push received with no data");
    return;
  }

  let title = "CIC Cloud 🎓";
  let body = "";
  let icon = "/logo.png";
  let badge = "/logo.png";
  let url = "/";

  try {
    const data = event.data.json();
    title = data.title || title;
    body = data.message || data.body || "";
    if (data.icon) icon = data.icon;
    if (data.link) url = data.link;
    if (data.data && data.data.url) url = data.data.url;
  } catch {
    body = event.data.text();
  }

  const options = {
    body,
    icon,
    badge,
    tag: "cic-notification-" + Date.now(),
    renotify: true,
    data: { url },
    vibrate: [200, 100, 200, 100, 200],
    requireInteraction: false,
    actions: [
      { action: "open", title: "فتح الموقع 🌐" },
      { action: "dismiss", title: "إغلاق ✕" },
    ],
  };

  event.waitUntil(
    self.registration.showNotification(title, options)
  );
});

// ─── 10) Notification Click Handler ─────────────────────────────────────────
self.addEventListener("notificationclick", (event) => {
  event.notification.close();

  if (event.action === "dismiss") return;

  const targetUrl = (event.notification.data && event.notification.data.url) || "/";

  event.waitUntil(
    self.clients.matchAll({ type: "window", includeUncontrolled: true }).then((clientList) => {
      for (const client of clientList) {
        if ("focus" in client) {
          client.focus();
          client.navigate && client.navigate(targetUrl);
          return;
        }
      }
      if (self.clients.openWindow) {
        return self.clients.openWindow(targetUrl);
      }
    })
  );
});

// ─── 11) Push Subscription Change (handles expiry/key rotation) ─────────────
self.addEventListener("pushsubscriptionchange", (event) => {
  console.log("[SW] Push subscription changed — notifying clients to re-subscribe");
  event.waitUntil(
    self.clients.matchAll({ includeUncontrolled: true, type: "window" }).then((clients) => {
      clients.forEach((client) => {
        client.postMessage({ type: "PUSH_SUBSCRIPTION_CHANGED" });
      });
    })
  );
});
